from __future__ import annotations

from .core import VALID_LEVELS, VALID_RENDERERS, VALID_SOURCE_KINDS, VALID_STATUSES


def union(values: set[str]) -> str:
    return " | ".join(f"'{value}'" for value in sorted(values))


def typescript_definitions() -> str:
    return f"""// Generated by local-dashboard-widget-sdk. Do not edit by hand.

export type WidgetStatus = {union(VALID_STATUSES)};
export type SourceKind = {union(VALID_SOURCE_KINDS)};
export type RendererKind = {union(VALID_RENDERERS)};
export type ThresholdLevel = {union(VALID_LEVELS)};

export interface DashboardSource {{
  kind: SourceKind;
  path?: string;
  url?: string;
  refreshMs?: number;
  [key: string]: unknown;
}}

export interface DashboardThreshold {{
  level: ThresholdLevel;
  gte?: number;
  lte?: number;
  label?: string;
}}

export interface DashboardRendererColumn {{
  key: string;
  label: string;
}}

export interface DashboardRenderer {{
  kind: RendererKind;
  valuePath?: string;
  unit?: string;
  thresholds?: DashboardThreshold[];
  columns?: DashboardRendererColumn[];
  seriesPath?: string;
  xPath?: string;
  yPath?: string;
  itemsPath?: string;
  component?: string;
  [key: string]: unknown;
}}

export interface DashboardLayout {{
  minW: number;
  minH: number;
  defaultW: number;
  defaultH: number;
}}

export interface DashboardWidgetManifest {{
  id: string;
  title: string;
  version: string;
  status: WidgetStatus;
  source: DashboardSource;
  renderer: DashboardRenderer;
  layout: DashboardLayout;
  tags?: string[];
  [key: string]: unknown;
}}

export interface DashboardPreset {{
  id: string;
  title: string;
  kind?: 'preset';
  renderer: RendererKind;
  layout?: DashboardLayout;
  defaults?: Record<string, unknown>;
  [key: string]: unknown;
}}

export type DashboardContract = DashboardWidgetManifest | DashboardPreset;
"""
